In [1]:
#Write a Python program to multiply a m x n matrix by n x a matrix and create a real matrix product.
import numpy as np
arr1 = np.random.random(15).reshape(5,3)
print("First_array(M X N):\n",arr1)
arr2 = np.random.random(6).reshape(3,2)
print("Second_array(N X A):\n",arr2)
my_array = np.dot(arr1,arr2,out = None)
print("Dot_Product:\n",my_array)

First_array(M X N):
 [[0.66746849 0.29573156 0.2450465 ]
 [0.04705812 0.92739922 0.48671402]
 [0.21848293 0.51953393 0.95707426]
 [0.5775262  0.38942162 0.31232334]
 [0.2000881  0.89675506 0.26957393]]
Second_array(N X A):
 [[0.44104448 0.47090323]
 [0.86949148 0.20607261]
 [0.98015814 0.08980091]]
Dot_Product:
 [[0.7917037  0.39726064]
 [1.30417715 0.25697876]
 [1.48617514 0.29589217]
 [0.89943979 0.380255  ]
 [1.13219372 0.30322677]]


In [2]:
#Write a NumPy program to check if each element of an array of your choice is composed of digits, 
#lower case letters, and upper case letters only.
import numpy as np
array_one = np.array(['Python', 'PHP' ,'JS' ,'Examples', 'html5' ,'5'])
print(array_one)
Digit = np.char.isdigit(array_one)
Lowercase = np.char.islower(array_one)
Uppercase = np.char.isupper(array_one)
print("Digits only =", Digit)
print("Lower cases only =", Lowercase)
print("Upper cases only =", Uppercase)
    

['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digits only = [False False False False False  True]
Lower cases only = [False False False False  True False]
Upper cases only = [False  True  True False False False]


In [8]:

#Write a program thatreads two space-separated positive integers X and Y as input and perform the following tasks:
import numpy as np
import random
X = int(input("Enter first value"))
Y = int(input("Enter second value"))
print (X)
print (Y)

#Creating 1st list
lst1 = []
no_of_ele = 16
i=1
while(no_of_ele!=0):
    lst1.append(i)
    i+=X
    no_of_ele -= 1
print(lst1)

#Creating 2nd list
lst2 = []
no_of_ele = 16
j=1
while(no_of_ele!=0):
    lst2.append(j)
    j+=Y
    no_of_ele -= 1
print(lst2)

#creating np1 and np2

np1 = np.array(lst1)
np2 = np.array(lst2)
print(np1)
print(np2)

#reshaping the array
np1 = np.array(lst1).reshape(4,4)
np2 = np.array(lst2).reshape(4,4)
print (np1)
print (np2)

#creating np3
np3 = np1-np2
print (np3)

#np3 into list elements
a = np.reshape(np3,16)
final_list = a.tolist()
print(a)

Enter first value7
Enter second value9
7
9
[1, 8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99, 106]
[1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91, 100, 109, 118, 127, 136]
[  1   8  15  22  29  36  43  50  57  64  71  78  85  92  99 106]
[  1  10  19  28  37  46  55  64  73  82  91 100 109 118 127 136]
[[  1   8  15  22]
 [ 29  36  43  50]
 [ 57  64  71  78]
 [ 85  92  99 106]]
[[  1  10  19  28]
 [ 37  46  55  64]
 [ 73  82  91 100]
 [109 118 127 136]]
[[  0  -2  -4  -6]
 [ -8 -10 -12 -14]
 [-16 -18 -20 -22]
 [-24 -26 -28 -30]]
[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]


In [16]:
#Write a Python program that takes two integer-NumPy arrays, P and Q of shape [3∗3]
import numpy as np
P = np.array([23, 56 ,87, 3, 6, 96 ,4 ,6, 78]).reshape(3,3)
Q = np.array([12, 34, 54, 7, 2, 54, 6, 2 ,78]).reshape(3,3)
print(P)
print(Q)
Z = P - Q
print(Z)

[[23 56 87]
 [ 3  6 96]
 [ 4  6 78]]
[[12 34 54]
 [ 7  2 54]
 [ 6  2 78]]
[[11 22 33]
 [-4  4 42]
 [-2  4  0]]
